version: '3.8'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: prodroot
      MYSQL_DATABASE: learning_spring
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend
    

  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATASOURCE_URL: jdbc:mysql://db:3306/learning_spring  # Use db as the hostname
      DATASOURCE_USERNAME: root
      DATASOURCE_PASSWORD: prodroot
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend
    entrypoint: [ "java", "-jar", "app.jar"]  # Wait for DB before starting app

networks:
  backend:
    driver: bridge
