server:
    port: 8001

spring:
    profiles:
        active: prod
---
spring:
    config:
        activate:
            on-profile: dev
    datasource:
        url: jdbc:mysql://localhost:3306/springboot-dev
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: Welcome to Spring Boot Application
--- 
spring:
    config:
        activate:
            on-profile: prod
    datasource:
        url: jdbc:mysql://localhost:3306/springboot-prod
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
welcome:
    message: Welcome to Spring Boot Application
