apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app-deployment
  namespace: spring
  labels:
    app: spring-boot-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
      - name: spring-boot-app
        image: yashsahsani/spring-learning:latest
        securityContext:  
          readOnlyRootFilesystem: true  
          runAsNonRoot: true
          allowPrivilegeEscalation: false
        env:
        - name: DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: spring-boot-app-config
              key: DATASOURCE_URL
        - name: DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: spring-boot-app-secret
              key: DATASOURCE_USERNAME
        - name: DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: spring-boot-app-secret
              key: DATASOURCE_PASSWORD
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: spring-boot-app-config
              key: SPRING_PROFILES_ACTIVE
        ports:
        - containerPort: 8080
        