name: build Maven

on:
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Java 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Install dependencies and run tests
      run: mvn clean install

    - name: Run tests with Maven
      run: mvn test

    - name: create jar file
      run: mvn clean package
    
  create-docker:
    runs-on: ubuntu-latest
    needs: test_and_build

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up Docker Hub Credentials
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }} .
    
    - name: Push Docker image to Docker Hub 
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest